<table class="grille-table">
	<tr><td class="grille-td no-border-top no-border-left"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top"></td><td class="grille-td no-border-top no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-left"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td"></td><td class="grille-td no-border-right"></td></tr>
	<tr><td class="grille-td no-border-bottom no-border-left"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom"></td><td class="grille-td no-border-bottom no-border-right"></td></tr>
</table>
